# Fonte
font_family      JetBrainsMono Nerd Font
bold_font        JetBrainsMono Nerd Font Bold
italic_font      JetBrainsMono Nerd Font Italic
font_size        8.0

# Janela
window_padding_width 12
hide_window_decorations yes
background_opacity 0.90

# Cursor
cursor                  #ff3333
cursor_shape            beam
cursor_blink_interval   0.5

# Scroll
scrollback_lines 10000

# Cores — tema Dark Red / Black
foreground              #e8d0d0
background              #0d0808

selection_foreground    #0d0808
selection_background    #cc2222

# Preto
color0  #1a0a0a
color8  #3d1515

# Vermelho
color1  #cc2222
color9  #ff3333

# Verde (apagado pra combinar)
color2  #6b3030
color10 #8b4040

# Amarelo
color3  #cc6622
color11 #e08040

# Azul (apagado)
color4  #4a2020
color12 #6b3535

# Magenta
color5  #992222
color13 #cc3333

# Ciano
color6  #7a3030
color14 #9b4444

# Branco
color7  #c8a8a8
color15 #e8d0d0

# Tabs
tab_bar_style powerline
tab_powerline_style slanted
active_tab_foreground   #0d0808
active_tab_background   #cc2222
inactive_tab_foreground #c8a8a8
inactive_tab_background #1a0a0a
